services:
  web:
    build: .
    container_name: marliz-sec-news
    restart: always
    ports:
      - "3005:3000"
    volumes:
      - ./backend/cybersec_news.db:/app/backend/cybersec_news.db
      - ./backend/uploads:/app/backend/uploads
    env_file:
      - .env
